const fa = {
    "Error": "خطایی رخ داده است",
    "InternalServerError": "خطای سروری",
    "InputValidationError": "لطفا مقادیر ورودی را با دقت وارد نمایید",
    "ResourceNotFound": "ریسورس یافت نشد",
    "InvalidGoogleIdToken": "توکن گوگل اشتباه هست",
    "PassengerAlreadyRegistered": "شما قبلا ثبت نام کرده اید",
    "ClientRequestBlockedTurnover": "بلاک شده به خاطر درخواست {{requestCode}}",
    "SystemRequestBlockedTurnover": "بلاک شده به خاطر درخواست {{requestCode}}",
    "ClientPaymentTurnover": "پرداخت",
    "DriverPaymentTurnover": "پرداخت",
    "SystemPaymentTurnover": "پرداخت توسط {{clientName}}",
    "ClientRequestTurnover": "برای درخواست {{requestCode}}",
    "SystemRequestTurnover": "برای درخواست {{requestCode}}",
    "DriverRequestTurnover": "برای درخواست {{requestCode}}",
    "DriverCommissionTurnover": "کمیسیون درخواست {{requestCode}}",
    "SystemCommissionTurnover": "کمیسیون درخواست {{requestCode}}",
    "RequestAlreadyAccepted": "راننده گرامی، این درخواست را راننده دیگری قبل از شما پذیرفت",
    "RequestExpired": "درخواست منقضی شده است",
    "RequestNotAllowedToAccept": "شما اجازه پذیرفتن این درخواست را ندارید",
    "OndemandRequestDriverArrived": "راننده رسید",
    "StateDescription:Pending": "در حال یافتن راننده",
    "StateDescription:Assigned": "پذیرفته شده",
    "StateDescription:Unassigned": "راننده ای درخواست را نپذیرفت",
    "StateDescription:Started": "در راه مبدا",
    "StateDescription:PickedUp": "در حال انجام",
    "StateDescription:Done": "تمام شده",
    "StateDescription:ClientCanceled": "لغو شده توسط مشتری",
    "StateDescription:DriverCanceled": "لغو شده توسط راننده",
    "StateDescription:Arrived": "راننده رسید",
    "StateDescription:SupportCanceled": "پشتیبانی لغو کرده است",
    "Driver:StateMessage:Pending": "در جست و جوی راننده",
    "Driver:StateMessage:Assigned": "راننده ای درخواست شما را پذیرفت",
    "Driver:StateMessage:Unassigned": "درخواست معتبر نمی باشد",
    "Driver:StateMessage:Started": "راننده در راه مبدا می باشد",
    "Driver:StateMessage:PickedUp": "راننده شروع به حرکت به سمت مقصد کرده است",
    "Driver:StateMessage:Done": "درخواس تمام شد",
    "Driver:StateMessage:ClientCanceled": "مشتری درخواست را لغو کرد",
    "Driver:StateMessage:DriverCanceled": "درخواست لفو شد",
    "Driver:StateMessage:Arrived": "راننده رسید",
    "Driver:StateMessage:SupportCanceled": "پشتیبانی لغو کرده است",
    "Client:StateMessage:Pending": "در حال جست و جوی راننده",
    "Client:StateMessage:Assigned": "مشتری گرامی، راننده ای درخواست شما را پذیرفت",
    "Client:StateMessage:Unassigned": "مشتری گرامی، هیچ راننده ای درخواست را نپذیرفت",
    "Client:StateMessage:Started": "راننده شروع به حرکت به سمت مبدا کرده است",
    "Client:StateMessage:PickedUp": "راننده شروع به حرکت به سمت مقصد کرده است",
    "Client:StateMessage:Done": "درخواست تمام شد",
    "Client:StateMessage:ClientCanceled": "درخواست لغو شد",
    "Client:StateMessage:DriverCanceled": "راننده درخواست را لغو کرد",
    "Client:StateMessage:Arrived": "راننده رسید",
    "Client:StateMessage:SupportCanceled": "پشتیبانی لغو کرده است",
    "ClientNotRegistered": "شما ثبت نام نکرده اید. لطفا ابتدا ثبت نام نمایید",
    "SmsLimitationError": "محدودیت در ارسال پیامک وجود دارد. بعدا امتحان نمایید",
    "ClientAlreadyRegistered": "شما قبلا ثبت نام کرده اید",
    "ServicetypeUnavailable": "هیچ خدماتی در دسترس نیست",
    "InvalidDriverPassword": "رمز عبور اشتباه است",
    "DriverNotRegistered": "شما ثبت نام نکرده اید. لطفا ابتدا ثبت نام نمایید",
    "InvalidVerificationCode": "کد فعالسازی نامعتبر است",
    "VerificationCodeExpired": "کد فعالسازی منقضی شده است",
    "AppInactive": "اپلیکیشن موقتا غیرفعال شده است. در حال تلاش برای رفع مشکل هستیم.",
    "AppForceUpdate": "برای استفاده از اپلیکیشن، لطفا آن را به آخرین نسخه منتشر شده بروزرسانی نمایید",
    "AppNormalUpdate": "به منظور استفاده از امکانات جدید برنامه، لطفا آن را به آخرین بروزرسانی نمایید",
    "DriverAlreadyRegistered": "شما قبلا ثبت نام کرده اید",
    "DriverNotAuthorizedWithMessage": "شما مجاز به فعالیت در سیستم نمی باشید: {{message}}",
    "DriverNotAuthorizedWithoutMessage": "شما مجاز به فعالیت در سیستم نمی باشید",
    "ClientPickupTime": "مدت {{duration}} دقیقه تا رسیدن راننده",
    "ClientFinishTime": "مدت {{duration}} دقیقه تا پایان درخواست",
    "DriverLowWalletCredit": "اعتبار کیف پول شما کم است، برای دریافت درخواست های جدید لطفا کیف پول خود را شارژ کنید",
    "notifyDriverSupportCanceled": "درخواست {{requestCode}} توسط پشتیبانی لغو شد",
    "notifyClientSupportCanceled": "درخواست {{requestCode}} توسط پشتیبانی لغو شد",
    "notifyClientRequestDone": "درخواست {{requestCode}} تمام شد",
    "notifyUnassigned": "هیچ راننده ای درخواست {{requestCode}} را نپذیرفت",
    "notifyDriverClientCanceled": "درخواست {{requestCode}} توسط مشتری لغو شد",
    "notifyDriversNewRequest": "درخواست جدید از مبدا {{pickupAddress}} به مقصد {{dropoffAddress}}",
    "notifyClientDriverAccepted": "درخواست {{requestCode}} توسط راننده پذیرفته شد ",
    "notifyClientReuqestStarted": "راننده درخواست {{requestCode}} را شروع کرد",
    "notifyClientReuqestPickedUp": "راننده حرکت به سمت مقصد درخواست {{requestCode}} را شروع کرد",
    "notifyClientDriverArrived": "راننده به مبدا درخواست {{requestCode}} رسید",
    "notifyClientDriverCanceled": "راننده درخواست {{requestCode}} را لغو کرد",
    "newRequest": "درخواست جدید",
    "DriverHasActiveCashout": "شما یک درخواست تسویه فعال دارید، لطفا تا بررسی درخواست فعلی صبر کنید.",
    "DriverLowCreditForCashOut": "شما اعتبار کافی برای ثبت درخواست تسویه حساب ندارید.",
    "InvalidClientPromotion": "کد تخفیف وارد شده اشتباه است",
    "ClientRequestPromotionTurnover": "تخفیف برای درخواست {{requestCode}}",
    "SystemRequestPromotionTurnover": "تخفیف برای درخواست {{requestCode}}",
    "newMessage": "پیام جدید",
    "callDriver": "تماس با راننده",
    "requestDetails": "جزئیات درخواست",
    "additionalServices": "خدمات اضافی",
    "ScheduleRequestNotAllowedToCancel": "شما مجاز به لغو درخواست رزروی نیستید",
    "CashOutStateDescription:Pending": "در حال بررسی",
    "CashOutStateDescription:Completed": "تمام شده",
    "CashOutStateDescription:Rejected": "رد شده",
    "DriverAlreadyLoggedIn": "شما با این حساب کاربری قبلا وارد شده اید، لطفا با پشتیبانی تماس بگیرید.",
    "ExceedMaxSurchargePrice": "مبلغ وارد شده بیشتر از حداکثر مبلغ تعریف شده برای این تعرفه می باشد.",
    baseFare: 'هزینه اولیه',
    promotion: 'تخفیف',
    total: 'مجموع',
    surcharges: 'هزینه های اضافی',
    DriverCashOutMinCredit: 'مبلغ درخواستی شما از حداقل اعتبار موجود کمتر است.',
    "RequestHistoryCreated": "ایجاد درخواست",
    "RequestHistoryUnassigned": "یافت نشدن راننده",
    "RequestHistoryAssigned": "تخصیص راننده",
    "RequestHistoryStarted": "شروع توسط راننده",
    "RequestHistoryArrived": "رسیدن راننده به مبدا",
    "RequestHistoryPickedUp": "تحویل در مبدا",
    "RequestHistoryDone": "اتمام درخواست",
    "RequestHistoryDoneDropoff": "انجام شدن مقصد {{index}}",
    "RequestHistoryClientFeedback": "فیدبک مشتری",
    "RequestHistoryAddPod": "ارسال اثبات تحویل در مقصد {{index}} ",
    "RequestHistoryClientCanceled": "کنسل درخواست توسط مشتری",
    "RequestHistoryDriverCanceled": "کنسل درخواست توسط راننده",
    "RequestHistorySuportCanceled": "کنسل درخواست توسط پشتیبانی",
    "RequestHistoryUpdated": "تغییر اطلاعات درخواست"
}

const en = {
    "Error": "An error occurred",
    "InternalServerError": "Server Fault!",
    "InputValidationError": "Fill the inputs carefully!",
    "ResourceNotFound": "Resource not found",
    "InvalidGoogleIdToken": "Invalid google id token",
    "PassengerAlreadyRegistered": "You are already signed up",
    "ClientRequestBlockedTurnover": "Blocked for request {{requestCode}}",
    "SystemRequestBlockedTurnover": "Blocked for request {{requestCode}}",
    "ClientPaymentTurnover": "Payment",
    "DriverPaymentTurnover": "Payment",
    "SystemPaymentTurnover": "Payment by {{clientName}}",
    "ClientRequestTurnover": "For request {{requestCode}}",
    "SystemRequestTurnover": "For request {{requestCode}}",
    "DriverRequestTurnover": "For request {{requestCode}}",
    "DriverCommissionTurnover": "Commission for request {{requestCode}}",
    "SystemCommissionTurnover": "Commission for request {{requestCode}}",
    "RequestAlreadyAccepted": "Dear driver, Request already accepted by another driver",
    "RequestExpired": "Request has been expired",
    "RequestNotAllowedToAccept": "Request not allowed to be accepted",
    "OndemandRequestDriverArrived": "Driver arrived",
    "StateDescription:Pending": "Assigning driver",
    "StateDescription:Assigned": "Accepted",
    "StateDescription:Unassigned": "Driver not found",
    "StateDescription:Started": "On the way",
    "StateDescription:PickedUp": "In progress",
    "StateDescription:Done": "Finished",
    "StateDescription:ClientCanceled": "Canceled by customer",
    "StateDescription:DriverCanceled": "Canceled by driver",
    "StateDescription:Arrived": "Driver arrived",
    "StateDescription:SupportCanceled": "Canceled by support",
    "Driver:StateMessage:Pending": "Searching for a driver",
    "Driver:StateMessage:Assigned": "A driver Accepted the request",
    "Driver:StateMessage:Unassigned": "This request is not valid anymore.",
    "Driver:StateMessage:Started": "The driver's on the way ",
    "Driver:StateMessage:PickedUp": "The driver keeps driving to the drop off location",
    "Driver:StateMessage:Done": "Request ended",
    "Driver:StateMessage:ClientCanceled": "Customer canceled the request",
    "Driver:StateMessage:DriverCanceled": "Request canceled",
    "Driver:StateMessage:Arrived": "Driver arrived",
    "Driver:StateMessage:SupportCanceled": "Canceled by support",
    "Client:StateMessage:Pending": "Searching for a driver",
    "Client:StateMessage:Assigned": "Dear customer, A driver accepted your request",
    "Client:StateMessage:Unassigned": "Dear customer, No driver found for the request",
    "Client:StateMessage:Started": "Driver on the way",
    "Client:StateMessage:PickedUp": "Driver picked up ",
    "Client:StateMessage:Done": "Request ended",
    "Client:StateMessage:ClientCanceled": "Request canceled",
    "Client:StateMessage:DriverCanceled": "Driver canceled the request",
    "Client:StateMessage:Arrived": "Driver arrived",
    "Client:StateMessage:SupportCanceled": "Canceled by support",
    "ClientNotRegistered": "You are not signed up. Please sign up first",
    "SmsLimitationError": "Sending sms Limitation Error",
    "ClientAlreadyRegistered": "You are already signed up",
    "ServicetypeUnavailable": "Service unavailable",
    "InvalidDriverPassword": "Your password is wrong",
    "DriverNotRegistered": "You are not signed up. Please sign up first",
    "InvalidVerificationCode": "Verification code isn't valid",
    "VerificationCodeExpired": "Verification code is expired",
    "AppInactive": "Our service is temproray unavailable. We're trying hard to fix it.",
    "AppForceUpdate": "To keep using app, you must update to newer version.",
    "AppNormalUpdate": "Update app for new features and other improvements",
    "DriverAlreadyRegistered": "You are already signed up",
    "DriverNotAuthorizedWithMessage": "You are not authorized: {{message}}",
    "DriverNotAuthorizedWithoutMessage": "You are not authorized",
    "ClientPickupTime": "{{duration}} min to pickup",
    "ClientFinishTime": "{{duration}} min to finish",
    "DriverLowWalletCredit": "Your wallet credit is low, please recharge your wallet to get new requests.",
    "notifyDriverSupportCanceled": "Request {{requestCode}} canceled by the support",
    "notifyClientSupportCanceled": "Request {{requestCode}} canceled by the support",
    "notifyClientRequestDone": "Request {{requestCode}} finished",
    "notifyUnassigned": "No driver found for the request {{requestCode}}",
    "notifyDriverClientCanceled": "Request {{requestCode}} canceled by the customer",
    "notifyDriversNewRequest": "New request from {{pickupAddress}} to the {{dropoffAddress}}",
    "notifyClientDriverAccepted": "Request {{requestCode}} accepted by a driver",
    "notifyClientReuqestStarted": "Driver started the request {{requestCode}}",
    "notifyClientReuqestPickedUp": "Driver picked up the request {{requestCode}}",
    "notifyClientDriverArrived": "Driver arrived to the pickup location of request {{requestCode}}",
    "notifyClientDriverCanceled": "Driver canceled the request {{requestCode}}",
    "newRequest": "New request",
    "DriverHasActiveCashout": "You already have an active cash out request, please wait until your request reviewed",
    "DriverLowCreditForCashOut": "Your wallet credit is low, and cannot submit a cashout request",
    "InvalidClientPromotion": "Promo code is not valid",
    "ClientRequestPromotionTurnover": "Promotion for request {{requestCode}}",
    "SystemRequestPromotionTurnover": "Promotion for request {{requestCode}}",
    "newMessage": "New message",
    "callDriver": "Call Driver",
    "requestDetails": "Request details",
    "additionalServices": "Additional services",
    "ScheduleRequestNotAllowedToCancel": "You are not allowed to cancel the request",
    "CashOutStateDescription:Pending": "Under review",
    "CashOutStateDescription:Completed": "Completed",
    "CashOutStateDescription:Rejected": "Rejected",
    "DriverAlreadyLoggedIn": "You already logged in into this account, please contact the support.",
    "ExceedMaxSurchargePrice": "Entered price exceeds the maximum legal price of the surcharge tarry",
    baseFare: 'Base fare',
    promotion: 'Promotion',
    total: 'Total',
    surcharges: 'Surcharge',
    DriverCashOutMinCredit: "Your requested amount is lower than the minimum credit.",
    "RequestHistoryCreated": "Created",
    "RequestHistoryUnassigned": "No Driver Founded",
    "RequestHistoryAssigned": "Driver Assigned",
    "RequestHistoryStarted": "Started",
    "RequestHistoryArrived": "Driver Arrived At Pickup",
    "RequestHistoryPickedUp": "Driver Picked Up The Parcel",
    "RequestHistoryDone": "Finished",
    "RequestHistoryDoneDropoff": "Dropoff {{index}} Done",
    "RequestHistoryClientFeedback": "Client Feedback",
    "RequestHistoryAddPod": "POD Addedd For Dropoff {{index}}",
    "RequestHistoryClientCanceled": "Client Canceled",
    "RequestHistoryDriverCanceled": "Driver Canceled",
    "RequestHistorySuportCanceled": "Support Canceled",
    "RequestHistoryUpdated": "Update Request Information"
}

export const Translations = {
    en, fa
};